///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RegressionWebinar
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RegressionWebinarRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("500842b0-20ff-45e5-a766-c2a0b75b7e03")]
    public partial class RegressionWebinarRepository : RepoGenBaseFolder
    {
        static RegressionWebinarRepository instance = new RegressionWebinarRepository();
        RegressionWebinarRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the RegressionWebinarRepository element repository.
        /// </summary>
        [RepositoryFolder("500842b0-20ff-45e5-a766-c2a0b75b7e03")]
        public static RegressionWebinarRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RegressionWebinarRepository() 
            : base("RegressionWebinarRepository", "/", null, 0, false, "500842b0-20ff-45e5-a766-c2a0b75b7e03", ".\\RepositoryImages\\RegressionWebinarRepository500842b0.rximgres")
        {
            _applicationundertest = new RegressionWebinarRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("500842b0-20ff-45e5-a766-c2a0b75b7e03")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("4abbc8fc-a1b3-403b-aaeb-efe61a477951")]
        public virtual RegressionWebinarRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RegressionWebinarRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("4abbc8fc-a1b3-403b-aaeb-efe61a477951")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _categoryInfo;
            RepoItemInfo _genderInfo;
            RepoItemInfo _inputtagaddInfo;
            RepoItemInfo _countInfo;
            RepoItemInfo _deleteInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "4abbc8fc-a1b3-403b-aaeb-efe61a477951", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName']", 30000, null, "a39dbf4e-2d32-4f62-9cb7-e6b3cc05f786");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", 30000, null, "8d3a4c9e-f258-4b83-b5f2-fb6126798d55");
                _categoryInfo = new RepoItemInfo(this, "Category", ".//select[#'Category']", 30000, null, "0b636e6a-d660-4ec7-a26c-b8a75daabc41");
                _genderInfo = new RepoItemInfo(this, "Gender", ".//td[#'gender']/table//input[@name='Gender' and @type='radio' and @value='male']", 30000, null, "88abcd44-9ffa-4db6-81fb-b02775c97eb5");
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", 30000, null, "aa1c45b4-ae5b-474a-9e51-32146cc90b85");
                _countInfo = new RepoItemInfo(this, "Count", ".//td[#'count']", 30000, null, "d67a6e7c-4d20-41bb-bcf2-418165966246");
                _deleteInfo = new RepoItemInfo(this, "Delete", ".//input[#'Delete']", 30000, null, "71df6874-ace2-414b-a0ae-a4c3b857e70d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4abbc8fc-a1b3-403b-aaeb-efe61a477951")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4abbc8fc-a1b3-403b-aaeb-efe61a477951")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("a39dbf4e-2d32-4f62-9cb7-e6b3cc05f786")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("a39dbf4e-2d32-4f62-9cb7-e6b3cc05f786")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("8d3a4c9e-f258-4b83-b5f2-fb6126798d55")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("8d3a4c9e-f258-4b83-b5f2-fb6126798d55")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Category item.
            /// </summary>
            [RepositoryItem("0b636e6a-d660-4ec7-a26c-b8a75daabc41")]
            public virtual Ranorex.SelectTag Category
            {
                get
                {
                    return _categoryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Category item info.
            /// </summary>
            [RepositoryItemInfo("0b636e6a-d660-4ec7-a26c-b8a75daabc41")]
            public virtual RepoItemInfo CategoryInfo
            {
                get
                {
                    return _categoryInfo;
                }
            }

            /// <summary>
            /// The Gender item.
            /// </summary>
            [RepositoryItem("88abcd44-9ffa-4db6-81fb-b02775c97eb5")]
            public virtual Ranorex.InputTag Gender
            {
                get
                {
                    return _genderInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Gender item info.
            /// </summary>
            [RepositoryItemInfo("88abcd44-9ffa-4db6-81fb-b02775c97eb5")]
            public virtual RepoItemInfo GenderInfo
            {
                get
                {
                    return _genderInfo;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("aa1c45b4-ae5b-474a-9e51-32146cc90b85")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("aa1c45b4-ae5b-474a-9e51-32146cc90b85")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }

            /// <summary>
            /// The Count item.
            /// </summary>
            [RepositoryItem("d67a6e7c-4d20-41bb-bcf2-418165966246")]
            public virtual Ranorex.TdTag Count
            {
                get
                {
                    return _countInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Count item info.
            /// </summary>
            [RepositoryItemInfo("d67a6e7c-4d20-41bb-bcf2-418165966246")]
            public virtual RepoItemInfo CountInfo
            {
                get
                {
                    return _countInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("71df6874-ace2-414b-a0ae-a4c3b857e70d")]
            public virtual Ranorex.InputTag Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("71df6874-ace2-414b-a0ae-a4c3b857e70d")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
